"""add city area and metadata to table

Revision ID: 317133145e33
Revises: cd04b7da7c3b
Create Date: 2025-06-15 02:05:43.557924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317133145e33'
down_revision: Union[str, None] = 'cd04b7da7c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('area', sa.BigInteger(), nullable=True))
    op.add_column('city_attributes', sa.Column('notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city_attributes', 'notes')
    op.drop_column('cities', 'area')
    # ### end Alembic commands ###
