"""Add CityAttribute table and user preferences

Revision ID: 5616b981c3ea
Revises: b1394801f249
Create Date: 2025-06-08 18:04:14.980063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5616b981c3ea'
down_revision: Union[str, None] = 'b1394801f249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'attribute_name', name='uq_city_attribute')
    )
    op.create_index(op.f('ix_city_attributes_attribute_name'), 'city_attributes', ['attribute_name'], unique=False)
    op.create_index(op.f('ix_city_attributes_city_id'), 'city_attributes', ['city_id'], unique=False)
    op.create_index(op.f('ix_city_attributes_id'), 'city_attributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_attributes_id'), table_name='city_attributes')
    op.drop_index(op.f('ix_city_attributes_city_id'), table_name='city_attributes')
    op.drop_index(op.f('ix_city_attributes_attribute_name'), table_name='city_attributes')
    op.drop_table('city_attributes')
    # ### end Alembic commands ###
