"""Add extra columns to cities table for better search

Revision ID: f35826018ede
Revises: 5616b981c3ea
Create Date: 2025-06-09 17:54:22.201961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35826018ede'
down_revision: Union[str, None] = '5616b981c3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name_normalized', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('cities', sa.Column('country_name', sa.String(), nullable=True))
    op.drop_index('ix_cities_country', table_name='cities')
    op.create_index(op.f('ix_cities_country_code'), 'cities', ['country_code'], unique=False)
    op.create_index(op.f('ix_cities_country_name'), 'cities', ['country_name'], unique=False)
    op.create_index(op.f('ix_cities_name_normalized'), 'cities', ['name_normalized'], unique=False)
    op.drop_column('cities', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cities_name_normalized'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_code'), table_name='cities')
    op.create_index('ix_cities_country', 'cities', ['country'], unique=False)
    op.drop_column('cities', 'country_name')
    op.drop_column('cities', 'country_code')
    op.drop_column('cities', 'name_normalized')
    # ### end Alembic commands ###
